#!/bin/bash

function install_composer() {
    echo "Configuring composer."
    
    mkdir -p ${ROOT_DIR}/composer/bin
    export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
    curl -s https://getcomposer.org/installer | php -- --quiet --install-dir=${ROOT_DIR}/composer/bin
}

function check_composer() {
    local composer_bin=${ROOT_DIR}/composer/bin/composer.phar

    if [[ ! -e  ${composer_bin} ]]; then
        echo "composer not installed."
        install_composer
    fi
}
