#!/bin/bash

function install_composer() {
    echo "Configuring composer."
    
    mkdir -p ${OPENSHIFT_DATA_DIR}/composer/bin
    export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
    curl -s https://getcomposer.org/installer | php -- --quiet --install-dir=${OPENSHIFT_DATA_DIR}/composer/bin
    
    echo "Running 'composer install' and 'php artisan migrate --force' ..."
    pushd ${OPENSHIFT_REPO_DIR}
    composer install --trace
    php artisan migrate --force
}

function check_composer() {
    local composer_bin=${OPENSHIFT_DATA_DIR}/composer/bin/composer.phar

    if [[ ! -e  ${composer_bin} ]]; then
        echo "composer not installed."
        install_composer
    fi
}
