#!/bin/bash

set -e

source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

BUILD_DIR=${OPENSHIFT_TMP_DIR}/build
NGINX_DIR=${OPENSHIFT_RUNTIME_DIR}/nginx/
PHP_DIR=${OPENSHIFT_RUNTIME_DIR}/php5/
TEMPLATE_DIR=${OPENSHIFT_REPO_DIR}/.openshift/tmpl

umask 077

mkdir -p ${BUILD_DIR}

echo "Pre-processing nginx config."
cp ${TEMPLATE_DIR}/nginx.conf.tmpl ${BUILD_DIR}/nginx.conf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/nginx.conf
cp ${BUILD_DIR}/nginx.conf ${NGINX_DIR}/conf/nginx.conf

echo "Pre-processing PHP-fpm config."
cp ${TEMPLATE_DIR}/php-fpm.conf.tmpl ${BUILD_DIR}/php-fpm.conf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/php-fpm.conf
cp ${BUILD_DIR}/php-fpm.conf ${PHP_DIR}/etc/php-fpm.conf

rm -rf ${BUILD_DIR}

bash_profile=${OPENSHIFT_DATA_DIR}/.bash_profile
echo "Copy bash profile."
cp ${TEMPLATE_DIR}/bash_profile.tmpl ${bash_profile}

#
# Fazendo deploy das configurações do Laravel
#

source $OPENSHIFT_CARTRIDGE_SDK_BASH

echo "Setting environment variables..."
export APP_ENV="${APPLICATION_ENV:-production}"
if [[ "${APPLICATION_ENV:-}" != "development" ]]; then
  export APP_DEBUG=false
else
  export APP_DEBUG=true
fi
if [ "$(type -t set_env_var)" == "function" ]; then
  set_env_var 'APP_ENV' $APP_ENV $OPENSHIFT_HOMEDIR/.env/user_vars
  set_env_var 'APP_DEBUG' $APP_DEBUG $OPENSHIFT_HOMEDIR/.env/user_vars
fi

if [ ! -z "$OPENSHIFT_APP_DNS" ]; then
  export APP_URL="$OPENSHIFT_APP_DNS"
  if [ "$(type -t set_env_var)" == "function" ]; then
    set_env_var 'APP_URL' $APP_URL $OPENSHIFT_HOMEDIR/.env/user_vars
  fi
fi

if [ ! -z "$OPENSHIFT_SECRET_TOKEN" ]; then
  export APP_KEY=${OPENSHIFT_SECRET_TOKEN:0:31}
  if [ "$(type -t set_env_var)" == "function" ]; then
    set_env_var 'APP_KEY' $APP_KEY $OPENSHIFT_HOMEDIR/.env/user_vars
  fi
fi

if [ ! -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]; then
  export DB_DRIVER="pgsql"
fi

if [ ! -z "$OPENSHIFT_MYSQL_DB_HOST" ]; then
  export DB_DRIVER="mysql"
fi

if [ -z "$DB_DRIVER" ]; then
  echo "Could not find the database cartridge.  Please run:"
  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.5"
  echo "or"
  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-9.2"
  echo "then make a sample commit (add whitespace somewhere) and re-push"
  exit 5
else
  echo "Database driver set to '$DB_DRIVER'..."
  if [ "$(type -t set_env_var)" == "function" ]; then
    set_env_var 'DB_DRIVER' $DB_DRIVER $OPENSHIFT_HOMEDIR/.env/user_vars
  fi
fi

echo "Migrating storage and log directories..."

#
# If this is initial installation, copy the default storage directory
# from official Laravel installation and remove the log directory
#
if [ ! -d ${OPENSHIFT_DATA_DIR}storage ]; then
  mv ${OPENSHIFT_REPO_DIR}storage ${OPENSHIFT_DATA_DIR}storage
  rm -rf ${OPENSHIFT_DATA_DIR}storage/logs
fi

# Create symlink to new storage directory location
ln -sf ${OPENSHIFT_DATA_DIR}storage   ${OPENSHIFT_REPO_DIR}storage

# Create a symlink to the new log directory location
ln -sf ${OPENSHIFT_LOG_DIR}   ${OPENSHIFT_DATA_DIR}storage/logs

# Use repository .env
if [  -f ${OPENSHIFT_REPO_DIR}.openshift/.env ]; then
  cp -f ${OPENSHIFT_REPO_DIR}.openshift/.env ${OPENSHIFT_REPO_DIR}/.env
fi

# If not exist vendor folder, run composer install
if [ ! -d ${OPENSHIFT_REPO_DIR}vendor ]; then
  composer install
  echo "Running 'php artisan migrate --force'..."
  pushd ${OPENSHIFT_REPO_DIR} > /dev/null
  php artisan migrate --force
  popd > /dev/null
fi
