#!/bin/bash

set -e

source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

echo 1>&2
echo "Running 'php artisan migrate --force'..." 1>&2
echo 1>&2
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
php artisan migrate --force
popd > /dev/null